const champions = {
  aatrox: {
    id: "aatrox",
    name: "Aatrox",
    height: 6.78,
    image: "assets/champions/aatrox.png",
  },
  ahri: {
    id: "ahri",
    name: "Ahri",
    height: 1.67,
    image: "assets/champions/ahri.png",
  },
  akali: {
    id: "akali",
    name: "Akali",
    height: 1.60,
    image: "assets/champions/akali.png",
  },
  akshan: {
    id: "akshan",
    name: "Akshan",
    height: 1.75,
    image: "assets/champions/akshan.png",
  },
  alistar: {
    id: "alistar",
    name: "Alistar",
    height: 3.18,
    image: "assets/champions/alistar.png",
  },
  ambessa: {
    id: "ambessa",
    name: "Ambessa",
    height: 1.75,
    image: "assets/champions/ambessa.png",
  },
  amumu: {
    id: "amumu",
    name: "Amumu",
    height: 1.09,
    image: "assets/champions/amumu.png",
  },
  anivia: {
    id: "anivia",
    name: "Anivia",
    height: 4.57,
    image: "assets/champions/anivia.png",
  },
  annie: {
    id: "annie",
    name: "Annie",
    height: 1.27,
    image: "assets/champions/annie.png",
  },
  aphelios: {
    id: "aphelios",
    name: "Aphelios",
    height: 1.83,
    image: "assets/champions/aphelios.png",
  },
  ashe: {
    id: "ashe",
    name: "Ashe",
    height: 1.75,
    image: "assets/champions/ashe.png",
  },
  aurelionsol: {
    id: "aurelionsol",
    name: "Aurelion Sol",
    height: 1000,
    image: "assets/champions/aurelion_sol.png",
  },
  aurora: {
    id: "aurora",
    name: "Aurora",
    height: 1.67,
    image: "assets/champions/aurora.png",
  },
  azir: {
    id: "azir",
    name: "Azir",
    height: 2.56,
    image: "assets/champions/azir.png",
  },
  bard: {
    id: "bard",
    name: "Bard",
    height: 1000,
    image: "assets/champions/bard.png",
  },
  belveth: {
    id: "belveth",
    name: "Bel'Veth",
    height: 3.05,
    image: "assets/champions/belveth.png",
  },
  blitzcrank: {
    id: "blitzcrank",
    name: "Blitzcrank",
    height: 2.74,
    image: "assets/champions/blitzcrank.png",
  },
  brand: {
    id: "brand",
    name: "Brand",
    height: 1.78,
    image: "assets/champions/brand.png",
  },
  braum: {
    id: "braum",
    name: "Braum",
    height: 2.26,
    image: "assets/champions/braum.png",
  },
  briar: {
    id: "briar",
    name: "Briar",
    height: 1.60,
    image: "assets/champions/briar.png",
  },
  caitlyn: {
    id: "caitlyn",
    name: "Caitlyn",
    height: 1.70,
    image: "assets/champions/caitlyn.png",
  },
  camille: {
    id: "camille",
    name: "Camille",
    height: 2.08,
    image: "assets/champions/camille.png",
  },
  cassiopeia: {
    id: "cassiopeia",
    name: "Cassiopeia",
    height: 3.96,
    image: "assets/champions/cassiopeia.png",
  },
  chogath: {
    id: "chogath",
    name: "Cho'Gath",
    height: 22.00,
    image: "assets/champions/chogath.png",
  },
  corki: {
    id: "corki",
    name: "Corki",
    height: 0.86,
    image: "assets/champions/corki.png",
  },
  darius: {
    id: "darius",
    name: "Darius",
    height: 1.95,
    image: "assets/champions/darius.png",
  },
  diana: {
    id: "diana",
    name: "Diana",
    height: 1.78,
    image: "assets/champions/diana.png",
  },
  drmundo: {
    id: "drmundo",
    name: "Dr. Mundo",
    height: 2.64,
    image: "assets/champions/drmundo.png",
  },
  draven: {
    id: "draven",
    name: "Draven",
    height: 1.85,
    image: "assets/champions/draven.png",
  },
  ekko: {
    id: "ekko",
    name: "Ekko",
    height: 1.75,
    image: "assets/champions/ekko.png",
  },
  elise: {
    id: "elise",
    name: "Elise",
    height: 1.85,
    image: "assets/champions/elise.png",
  },
  evelynn: {
    id: "evelynn",
    name: "Evelynn",
    height: 1.64,
    image: "assets/champions/evelynn.png",
  },
  ezreal: {
    id: "ezreal",
    name: "Ezreal",
    height: 1.72,
    image: "assets/champions/ezreal.png",
  },
  fiddlesticks: {
    id: "fiddlesticks",
    name: "Fiddlesticks",
    height: 1.83,
    image: "assets/champions/fiddlesticks.png",
  },
  fiora: {
    id: "fiora",
    name: "Fiora",
    height: 1.80,
    image: "assets/champions/fiora.png",
  },
  fizz: {
    id: "fizz",
    name: "Fizz",
    height: 0.91,
    image: "assets/champions/fizz.png",
  },
  galio: {
    id: "galio",
    name: "Galio",
    height: 48.80,
    image: "assets/champions/galio.png",
  },
  gangplank: {
    id: "gangplank",
    name: "Gangplank",
    height: 1.83,
    image: "assets/champions/gangplank.png",
  },
  garen: {
    id: "garen",
    name: "Garen",
    height: 1.95,
    image: "assets/champions/garen.png",
  },
  gnar: {
    id: "gnar",
    name: "Gnar",
    height: 0.73,
    image: "assets/champions/gnar.png",
  },
  gragas: {
    id: "gragas",
    name: "Gragas",
    height: 2.18,
    image: "assets/champions/gragas.png",
  },
  graves: {
    id: "graves",
    name: "Graves",
    height: 1.75,
    image: "assets/champions/graves.png",
  },
  gwen: {
    id: "gwen",
    name: "Gwen",
    height: 1.60,
    image: "assets/champions/gwen.png",
  },
  hecarim: {
    id: "hecarim",
    name: "Hecarim",
    height: 2.74,
    image: "assets/champions/hecarim.png",
  },
  heimerdinger: {
    id: "heimerdinger",
    name: "Heimerdinger",
    height: 0.96,
    image: "assets/champions/heimerdinger.png",
  },
  hwei: {
    id: "hwei",
    name: "Hwei",
    height: 1.78,
    image: "assets/champions/hwei.png",
  },
  illaoi: {
    id: "illaoi",
    name: "Illaoi",
    height: 1.95,
    image: "assets/champions/illaoi.png",
  },
  irelia: {
    id: "irelia",
    name: "Irelia",
    height: 1.72,
    image: "assets/champions/irelia.png",
  },
  ivern: {
    id: "ivern",
    name: "Ivern",
    height: 3.00,
    image: "assets/champions/ivern.png",
  },
  janna: {
    id: "janna",
    name: "Janna",
    height: 1.71,
    image: "assets/champions/janna.png",
  },
  jarvaniv: {
    id: "jarvaniv",
    name: "Jarvan IV",
    height: 1.90,
    image: "assets/champions/jarvan_iv.png",
  },
  jax: {
    id: "jax",
    name: "Jax",
    height: 1.88,
    image: "assets/champions/jax.png",
  },
  jayce: {
    id: "jayce",
    name: "Jayce",
    height: 1.83,
    image: "assets/champions/jayce.png",
  },
  jhin: {
    id: "jhin",
    name: "Jhin",
    height: 1.93,
    image: "assets/champions/jhin.png",
  },
  jinx: {
    id: "jinx",
    name: "Jinx",
    height: 1.60,
    image: "assets/champions/jinx.png",
  },
  ksante: {
    id: "ksante",
    name: "K'Sante",
    height: 2.01,
    image: "assets/champions/ksante.png",
  },
  kaisa: {
    id: "kaisa",
    name: "Kai'Sa",
    height: 1.67,
    image: "assets/champions/kaisa.png",
  },
  kalista: {
    id: "kalista",
    name: "Kalista",
    height: 1.78,
    image: "assets/champions/kalista.png",
  },
  karma: {
    id: "karma",
    name: "Karma",
    height: 1.72,
    image: "assets/champions/karma.png",
  },
  karthus: {
    id: "karthus",
    name: "Karthus",
    height: 1.60,
    image: "assets/champions/karthus.png",
  },
  kassadin: {
    id: "kassadin",
    name: "Kassadin",
    height: 1.75,
    image: "assets/champions/kassadin.png",
  },
  katarina: {
    id: "katarina",
    name: "Katarina",
    height: 1.65,
    image: "assets/champions/katarina.png",
  },
  kayle: {
    id: "kayle",
    name: "Kayle",
    height: 1.67,
    image: "assets/champions/kayle.png",
  },
  kayn: {
    id: "kayn",
    name: "Kayn",
    height: 1.82,
    image: "assets/champions/kayn.png",
  },
  kennen: {
    id: "kennen",
    name: "Kennen",
    height: 0.78,
    image: "assets/champions/kennen.png",
  },
  khazix: {
    id: "khazix",
    name: "Kha'Zix",
    height: 1.93,
    image: "assets/champions/khazix.png",
  },
  kindred: {
    id: "kindred",
    name: "Kindred",
    height: 1.22,
    image: "assets/champions/kindred.png",
  },
  kled: {
    id: "kled",
    name: "Kled",
    height: 0.91,
    image: "assets/champions/kled.png",
  },
  kogmaw: {
    id: "kogmaw",
    name: "Kog'Maw",
    height: 2.43,
    image: "assets/champions/kogmaw.png",
  },
  leblanc: {
    id: "leblanc",
    name: "LeBlanc",
    height: 1.65,
    image: "assets/champions/leblanc.png",
  },
  leesin: {
    id: "leesin",
    name: "Lee Sin",
    height: 1.67,
    image: "assets/champions/lee_sin.png",
  },
  leona: {
    id: "leona",
    name: "Leona",
    height: 1.85,
    image: "assets/champions/leona.png",
  },
  lillia: {
    id: "lillia",
    name: "Lillia",
    height: 1.69,
    image: "assets/champions/lillia.png",
  },
  lissandra: {
    id: "lissandra",
    name: "Lissandra",
    height: 1.93,
    image: "assets/champions/lissandra.png",
  },
  locke: {
    id: "locke",
    name: "Locke",
    height: 1.82,
    image: "assets/champions/locke.png",
  },
  lucian: {
    id: "lucian",
    name: "Lucian",
    height: 1.83,
    image: "assets/champions/lucian.png",
  },
  lulu: {
    id: "lulu",
    name: "Lulu",
    height: 0.76,
    image: "assets/champions/lulu.png",
  },
  lux: {
    id: "lux",
    name: "Lux",
    height: 1.77,
    image: "assets/champions/lux.png",
  },
  malphite: {
    id: "malphite",
    name: "Malphite",
    height: 103.60,
    image: "assets/champions/malphite.png",
  },
  malzahar: {
    id: "malzahar",
    name: "Malzahar",
    height: 1.67,
    image: "assets/champions/malzahar.png",
  },
  maokai: {
    id: "maokai",
    name: "Maokai",
    height: 6.70,
    image: "assets/champions/maokai.png",
  },
  masteryi: {
    id: "masteryi",
    name: "Master Yi",
    height: 1.80,
    image: "assets/champions/master_yi.png",
  },
  mel: {
    id: "mel",
    name: "Mel",
    height: 1.72,
    image: "assets/champions/mel.png",
  },
  milio: {
    id: "milio",
    name: "Milio",
    height: 1.55,
    image: "assets/champions/milio.png",
  },
  missfortune: {
    id: "missfortune",
    name: "Miss Fortune",
    height: 1.67,
    image: "assets/champions/miss_fortune.png",
  },
  mordekaiser: {
    id: "mordekaiser",
    name: "Mordekaiser",
    height: 3.66,
    image: "assets/champions/mordekaiser.png",
  },
  morgana: {
    id: "morgana",
    name: "Morgana",
    height: 1.65,
    image: "assets/champions/morgana.png",
  },
  naafiri: {
    id: "naafiri",
    name: "Naafiri",
    height: 2.13,
    image: "assets/champions/naafiri.png",
  },
  nami: {
    id: "nami",
    name: "Nami",
    height: 1.88,
    image: "assets/champions/nami.png",
  },
  nasus: {
    id: "nasus",
    name: "Nasus",
    height: 2.74,
    image: "assets/champions/nasus.png",
  },
  nautilus: {
    id: "nautilus",
    name: "Nautilus",
    height: 12.00,
    image: "assets/champions/nautilus.png",
  },
  neeko: {
    id: "neeko",
    name: "Neeko",
    height: 1.44,
    image: "assets/champions/neeko.png",
  },
  nidalee: {
    id: "nidalee",
    name: "Nidalee",
    height: 1.67,
    image: "assets/champions/nidalee.png",
  },
  nilah: {
    id: "nilah",
    name: "Nilah",
    height: 1.70,
    image: "assets/champions/nilah.png",
  },
  nocturne: {
    id: "nocturne",
    name: "Nocturne",
    height: 2.12,
    image: "assets/champions/nocturne.png",
  },
  nunu: {
    id: "nunu",
    name: "Nunu",
    height: 1.32,
    image: "assets/champions/nunu.png",
  },
  olaf: {
    id: "olaf",
    name: "Olaf",
    height: 1.80,
    image: "assets/champions/olaf.png",
  },
  orianna: {
    id: "orianna",
    name: "Orianna",
    height: 1.72,
    image: "assets/champions/orianna.png",
  },
  ornn: {
    id: "ornn",
    name: "Ornn",
    height: 81.00,
    image: "assets/champions/ornn.png",
  },
  pantheon: {
    id: "pantheon",
    name: "Pantheon",
    height: 1.75,
    image: "assets/champions/pantheon.png",
  },
  poppy: {
    id: "poppy",
    name: "Poppy",
    height: 0.96,
    image: "assets/champions/poppy.png",
  },
  pyke: {
    id: "pyke",
    name: "Pyke",
    height: 1.78,
    image: "assets/champions/pyke.png",
  },
  qiyana: {
    id: "qiyana",
    name: "Qiyana",
    height: 1.52,
    image: "assets/champions/qiyana.png",
  },
  quinn: {
    id: "quinn",
    name: "Quinn",
    height: 1.73,
    image: "assets/champions/quinn.png",
  },
  rakan: {
    id: "rakan",
    name: "Rakan",
    height: 1.75,
    image: "assets/champions/rakan.png",
  },
  rammus: {
    id: "rammus",
    name: "Rammus",
    height: 0.91,
    image: "assets/champions/rammus.png",
  },
  reksai: {
    id: "reksai",
    name: "Rek'Sai",
    height: 9.10,
    image: "assets/champions/reksai.png",
  },
  rell: {
    id: "rell",
    name: "Rell",
    height: 1.70,
    image: "assets/champions/rell.png",
  },
  renataglasc: {
    id: "renataglasc",
    name: "Renata Glasc",
    height: 1.83,
    image: "assets/champions/renata_glasc.png",
  },
  renekton: {
    id: "renekton",
    name: "Renekton",
    height: 2.74,
    image: "assets/champions/renekton.png",
  },
  rengar: {
    id: "rengar",
    name: "Rengar",
    height: 2.03,
    image: "assets/champions/rengar.png",
  },
  riven: {
    id: "riven",
    name: "Riven",
    height: 1.80,
    image: "assets/champions/riven.png",
  },
  rumble: {
    id: "rumble",
    name: "Rumble",
    height: 0.78,
    image: "assets/champions/rumble.png",
  },
  ryze: {
    id: "ryze",
    name: "Ryze",
    height: 1.72,
    image: "assets/champions/ryze.png",
  },
  samira: {
    id: "samira",
    name: "Samira",
    height: 1.77,
    image: "assets/champions/samira.png",
  },
  sejuani: {
    id: "sejuani",
    name: "Sejuani",
    height: 1.83,
    image: "assets/champions/sejuani.png",
  },
  senna: {
    id: "senna",
    name: "Senna",
    height: 1.70,
    image: "assets/champions/senna.png",
  },
  seraphine: {
    id: "seraphine",
    name: "Seraphine",
    height: 1.60,
    image: "assets/champions/seraphine.png",
  },
  sett: {
    id: "sett",
    name: "Sett",
    height: 1.92,
    image: "assets/champions/sett.png",
  },
  shaco: {
    id: "shaco",
    name: "Shaco",
    height: 1.65,
    image: "assets/champions/shaco.png",
  },
  shen: {
    id: "shen",
    name: "Shen",
    height: 1.72,
    image: "assets/champions/shen.png",
  },
  shyvana: {
    id: "shyvana",
    name: "Shyvana",
    height: 1.67,
    image: "assets/champions/shyvana.png",
  },
  singed: {
    id: "singed",
    name: "Singed",
    height: 1.90,
    image: "assets/champions/singed.png",
  },
  sion: {
    id: "sion",
    name: "Sion",
    height: 2.75,
    image: "assets/champions/sion.png",
  },
  sivir: {
    id: "sivir",
    name: "Sivir",
    height: 1.72,
    image: "assets/champions/sivir.png",
  },
  skarner: {
    id: "skarner",
    name: "Skarner",
    height: 4.88,
    image: "assets/champions/skarner.png",
  },
  smolder: {
    id: "smolder",
    name: "Smolder",
    height: 1.33,
    image: "assets/champions/smolder.png",
  },
  sona: {
    id: "sona",
    name: "Sona",
    height: 1.67,
    image: "assets/champions/sona.png",
  },
  soraka: {
    id: "soraka",
    name: "Soraka",
    height: 1.88,
    image: "assets/champions/soraka.png",
  },
  swain: {
    id: "swain",
    name: "Swain",
    height: 1.80,
    image: "assets/champions/swain.png",
  },
  sylas: {
    id: "sylas",
    name: "Sylas",
    height: 1.90,
    image: "assets/champions/sylas.png",
  },
  syndra: {
    id: "syndra",
    name: "Syndra",
    height: 1.67,
    image: "assets/champions/syndra.png",
  },
  tahmkench: {
    id: "tahmkench",
    name: "Tahm Kench",
    height: 2.88,
    image: "assets/champions/tahm_kench.png",
  },
  taliyah: {
    id: "taliyah",
    name: "Taliyah",
    height: 1.75,
    image: "assets/champions/taliyah.png",
  },
  talon: {
    id: "talon",
    name: "Talon",
    height: 1.72,
    image: "assets/champions/talon.png",
  },
  taric: {
    id: "taric",
    name: "Taric",
    height: 1.88,
    image: "assets/champions/taric.png",
  },
  teemo: {
    id: "teemo",
    name: "Teemo",
    height: 0.81,
    image: "assets/champions/teemo.png",
  },
  thresh: {
    id: "thresh",
    name: "Thresh",
    height: 2.44,
    image: "assets/champions/thresh.png",
  },
  tristana: {
    id: "tristana",
    name: "Tristana",
    height: 0.81,
    image: "assets/champions/tristana.png",
  },
  trundle: {
    id: "trundle",
    name: "Trundle",
    height: 4.57,
    image: "assets/champions/trundle.png",
  },
  tryndamere: {
    id: "tryndamere",
    name: "Tryndamere",
    height: 1.85,
    image: "assets/champions/tryndamere.png",
  },
  twistedfate: {
    id: "twistedfate",
    name: "Twisted Fate",
    height: 1.85,
    image: "assets/champions/twisted_fate.png",
  },
  twitch: {
    id: "twitch",
    name: "Twitch",
    height: 1.09,
    image: "assets/champions/twitch.png",
  },
  udyr: {
    id: "udyr",
    name: "Udyr",
    height: 1.78,
    image: "assets/champions/udyr.png",
  },
  urgot: {
    id: "urgot",
    name: "Urgot",
    height: 3.05,
    image: "assets/champions/urgot.png",
  },
  varus: {
    id: "varus",
    name: "Varus",
    height: 1.70,
    image: "assets/champions/varus.png",
  },
  vayne: {
    id: "vayne",
    name: "Vayne",
    height: 1.75,
    image: "assets/champions/vayne.png",
  },
  veigar: {
    id: "veigar",
    name: "Veigar",
    height: 0.74,
    image: "assets/champions/veigar.png",
  },
  velkoz: {
    id: "velkoz",
    name: "Vel'Koz",
    height: 9.14,
    image: "assets/champions/velkoz.png",
  },
  vex: {
    id: "vex",
    name: "Vex",
    height: 0.81,
    image: "assets/champions/vex.png",
  },
  vi: {
    id: "vi",
    name: "Vi",
    height: 1.75,
    image: "assets/champions/vi.png",
  },
  viego: {
    id: "viego",
    name: "Viego",
    height: 1.90,
    image: "assets/champions/viego.png",
  },
  viktor: {
    id: "viktor",
    name: "Viktor",
    height: 1.88,
    image: "assets/champions/viktor.png",
  },
  vladimir: {
    id: "vladimir",
    name: "Vladimir",
    height: 1.90,
    image: "assets/champions/vladimir.png",
  },
  volibear: {
    id: "volibear",
    name: "Volibear",
    height: 9.14,
    image: "assets/champions/volibear.png",
  },
  warwick: {
    id: "warwick",
    name: "Warwick",
    height: 2.33,
    image: "assets/champions/warwick.png",
  },
  wukong: {
    id: "wukong",
    name: "Wukong",
    height: 1.88,
    image: "assets/champions/wukong.png",
  },
  xayah: {
    id: "xayah",
    name: "Xayah",
    height: 1.65,
    image: "assets/champions/xayah.png",
  },
  xerath: {
    id: "xerath",
    name: "Xerath",
    height: 4.57,
    image: "assets/champions/xerath.png",
  },
  xinzhao: {
    id: "xinzhao",
    name: "Xin Zhao",
    height: 1.72,
    image: "assets/champions/xin_zhao.png",
  },
  yasuo: {
    id: "yasuo",
    name: "Yasuo",
    height: 1.80,
    image: "assets/champions/yasuo.png",
  },
  yone: {
    id: "yone",
    name: "Yone",
    height: 1.91,
    image: "assets/champions/yone.png",
  },
  yorick: {
    id: "yorick",
    name: "Yorick",
    height: 1.85,
    image: "assets/champions/yorick.png",
  },
  yunara: {
    id: "yunara",
    name: "Yunara",
    height: 1.67,
    image: "assets/champions/yunara.png",
  },
  yuumi: {
    id: "yuumi",
    name: "Yuumi",
    height: 0.20,
    image: "assets/champions/yuumi.png",
  },
  zaahen: {
    id: "zaahen",
    name: "Zaahen",
    height: 2.10,
    image: "assets/champions/zaahen.png",
  },
  zac: {
    id: "zac",
    name: "Zac",
    height: 2.5,
    image: "assets/champions/zac.png",
  },
  zed: {
    id: "zed",
    name: "Zed",
    height: 1.78,
    image: "assets/champions/zed.png",
  },
  zeri: {
    id: "zeri",
    name: "Zeri",
    height: 1.65,
    image: "assets/champions/zeri.png",
  },
  ziggs: {
    id: "ziggs",
    name: "Ziggs",
    height: 0.76,
    image: "assets/champions/ziggs.png",
  },
  zilean: {
    id: "zilean",
    name: "Zilean",
    height: 1.85,
    image: "assets/champions/zilean.png",
  },
  zoe: {
    id: "zoe",
    name: "Zoe",
    height: 1.44,
    image: "assets/champions/zoe.png",
  },
  zyra: {
    id: "zyra",
    name: "Zyra",
    height: 1.80,
    image: "assets/champions/zyra.png",
  },
};
